# Choosing the right model for regression problem
r squared = 1 - (Sum(y(true) - y(pred)) squered ) / (Sum(y(pred) - y(mean)) squered)

In [2]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import sklearn

In [4]:
from sklearn.linear_model import Ridge
from sklearn.datasets import fetch_california_housing

housing_dataset = fetch_california_housing()
housing_dataset

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [8]:
housing_df = pd.DataFrame(housing_dataset.data, columns=housing_dataset.feature_names)
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [11]:
housing_df["Target"] = housing_dataset.target
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [12]:
from sklearn.model_selection import train_test_split 
X = housing_df.drop("Target", axis = 1)
y = housing_df["Target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
ridge = Ridge(random_state=42)
ridge.fit(X_train, y_train)

In [16]:
ridge.score(X_test, y_test)

0.5758549611440126

## If that doesn't work, choose another model / estimator

In [18]:
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [19]:
X = housing_df.drop("Target", axis = 1)
y = housing_df["Target"]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [23]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=42)

In [24]:
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [28]:
rf.score(X_test, y_test)

0.7911837225726758

# Choose the right model for classification problem

In [30]:
heart_disease = pd.read_csv("./data/heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

## Linear support vector classification

In [46]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=42, max_iter=1000)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.8688524590163934

## If that doesn't work, choose another model / estimator

In [54]:
heart_disease["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [60]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
clf = RandomForestClassifier(random_state=42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf.fit(X_train, y_train)

y_preds = clf.predict(X_test)

score = accuracy_score(y_test, y_preds)
score

0.8360655737704918

# Fit the model and use it to make predictions on out data
2 ways to make predictions
* 1. `predict()`
* 2. `predict_proba()`

In [61]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
clf = RandomForestClassifier(random_state=42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf.fit(X_train, y_train)

y_preds = clf.predict(X_test)

In [62]:
y_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [68]:
y_test_ndarray = np.array(y_test)
y_test_ndarray

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [86]:
comparing = y_test_ndarray == y_preds
comparing

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [90]:
counter = 0
for i in comparing:
    if i == True :
        counter = counter + 1
counter

51

In [92]:
np.mean(y_test_ndarray == y_preds)

np.float64(0.8360655737704918)

## predict() vs predict_proba()

## `predict()`

In [ ]:
heart_disease = pd.read_csv("./data/heart-disease.csv")
X = heart_disease.drop("target", axis = 1)
y = heart_disease["target"]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
svc = LinearSVC(random_state=42)
svc.fit(X_train, y_train)
y_preds = svc.predict(X_test)
accuracy_score(y_test, y_preds)

0.8688524590163934

## `predict_proba`

In [112]:
heart_disease = pd.read_csv("./data/heart-disease.csv")
X = heart_disease.drop("target", axis = 1)
y = heart_disease["target"]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)
y_preds = clf.predict_proba(X_test)
y_preds[-5:]

array([[0.59, 0.41],
       [0.06, 0.94],
       [0.86, 0.14],
       [1.  , 0.  ],
       [0.81, 0.19]])

In [125]:
y_preds_df = pd.DataFrame(y_preds)
y_preds_df = y_preds_df.sample(frac = 1)
y_preds_df

       0     1
28  0.90  0.10
55  0.90  0.10
6   0.36  0.64
19  0.94  0.06
7   0.95  0.05
..   ...   ...
20  0.54  0.46
31  0.91  0.09
52  0.15  0.85
17  0.92  0.08
5   0.16  0.84

[61 rows x 2 columns]

In [128]:
y_preds_df.iloc[-5:]

       0     1
20  0.54  0.46
31  0.91  0.09
52  0.15  0.85
17  0.92  0.08
5   0.16  0.84

In [5]:
import pandas as pd
import numpy as np
import sklearn
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing

housing_dataset = fetch_california_housing()
housing_dataset

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [6]:
housing_df = pd.DataFrame(housing_dataset.data, columns = housing_dataset["feature_names"])
housing_df

       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88    -122.23
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86    -122.22
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85    -122.24
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85    -122.25
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85    -122.25
...       ...       ...       ...        ...         ...       ...       ...        ...
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48    -121.09
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49    -121.21
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43    -121.22
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43    -121.32
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37    -121.24

[20640 rows x 8 columns]

In [9]:
housing_df["Target"] = housing_dataset["target"]
housing_df.head()

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  Target
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88    -122.23   4.526
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86    -122.22   3.585
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85    -122.24   3.521
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85    -122.25   3.413
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85    -122.25   3.422

In [13]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X = housing_df.drop("Target", axis=1)
y = housing_df["Target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

rg = RandomForestRegressor()

rg.fit(X_train, y_train)

y_preds = rg.predict(X_test)

y_preds[:10]

array([1.17125  , 1.56553  , 0.53857  , 2.3508011, 1.59376  , 0.97503  ,
       2.6109903, 3.8136225, 3.3224711, 3.2309305])

In [14]:
mean_absolute_error(y_test, y_preds)

0.3210857224563955

In [15]:
mean_squared_error(y_test, y_preds)

0.2499349658146655

In [16]:
root_mean_squared_error(y_test, y_preds)

0.49993496158467005

# Evaluating a machine learning model / estimator
Three ways to evaluate SKLearn estimators

  1 Estimator's built-in `score` method
  
  2 The `scoring` parameter
  
  3 Metric functions

### Build-in score method

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X = housing_df.drop("Target", axis=1)
y = housing_df["Target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

rg = RandomForestRegressor()

rg.fit(X_train, y_train)

RandomForestRegressor()

In [27]:
y_test_mean = y_test.mean()
y_test

4057     3.591
9531     0.831
18130    3.544
17456    1.283
2921     0.700
         ...
13411    1.134
9594     0.988
9487     1.429
2892     0.555
18057    4.158
Name: Target, Length: 4128, dtype: float64

In [28]:
y_test_new = pd.Series(y_test_mean, index = y_test.index)
y_test_new

4057     2.049874
9531     2.049874
18130    2.049874
17456    2.049874
2921     2.049874
           ...
13411    2.049874
9594     2.049874
9487     2.049874
2892     2.049874
18057    2.049874
Length: 4128, dtype: float64

In [29]:
rg.score(X_test, y_test_new)

-5.161218412674495e+30

### The scoring parameter ( Cross validation score )

In [43]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X = housing_df.drop("Target", axis=1)
y = housing_df["Target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

rg = RandomForestRegressor()

rg.fit(X_train, y_train)

RandomForestRegressor()

In [44]:
score = rg.score(X_test, y_test)
score

0.814996984909705

In [45]:
result = cross_val_score(rg, X, y, scoring = None)
result

array([0.51055297, 0.70617763, 0.74112384, 0.62790968, 0.68014162])

In [49]:
score, np.mean(result)

(0.814996984909705, np.float64(0.6531811510063447))

# Classification model evaulation metrics
1. `Accuracy`
2.  `Under area ROC curve`
3.  `Confusion matrix`
4.  `Classification raport`

### Accuracy

In [25]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

heart_disease_dataset = pd.read_csv("./data/heart-disease.csv")
heart_disease_dataset.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1        0      150      0      2.3      0   0     1       1
1   37    1   2       130   250    0        1      187      0      3.5      0   0     2       1
2   41    0   1       130   204    0        0      172      0      1.4      2   0     2       1
3   56    1   1       120   236    0        1      178      0      0.8      2   0     2       1
4   57    0   0       120   354    0        1      163      1      0.6      2   0     2       1

In [26]:
X = heart_disease_dataset.drop("target", axis=1)
y = heart_disease_dataset["target"]

X, y

(     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal
 0     63    1   3       145   233    1        0      150      0      2.3      0   0     1
 1     37    1   2       130   250    0        1      187      0      3.5      0   0     2
 2     41    0   1       130   204    0        0      172      0      1.4      2   0     2
 3     56    1   1       120   236    0        1      178      0      0.8      2   0     2
 4     57    0   0       120   354    0        1      163      1      0.6      2   0     2
 ..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...    ...  ..   ...
 298   57    0   0       140   241    0        1      123      1      0.2      1   0     3
 299   45    1   3       110   264    0        1      132      0      1.2      1   0     3
 300   68    1   0       144   193    1        1      141      0      3.4      1   2     3
 301   57    1   0       130   131    0        1      115      1      1.2      1   1     3
 302   57    0   1       130   236    0        0      174      0      0.0      1   1     2

 [303 rows x 13 columns],
 0      1
 1      1
 2      1
 3      1
 4      1
       ..
 298    0
 299    0
 300    0
 301    0
 302    0
 Name: target, Length: 303, dtype: int64)

In [28]:
clf = RandomForestClassifier(n_estimators=100, random_state=42)
score = cross_val_score(clf, X, y, scoring=None, cv=5)

In [29]:
np.mean(score)

np.float64(0.8381967213114756)