# Evaluating a regression model

In [1]:
import pandas as pd 
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import fetch_california_housing
housing_dataset = fetch_california_housing()
housing_dataset

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [3]:
housing_df = pd.DataFrame(housing_dataset.data, columns=housing_dataset.feature_names)
housing_df["Target"] = housing_dataset.target
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [4]:
X = housing_df.drop("Target", axis=1)
y = housing_df["Target"]
y.head(10)

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
5    2.697
6    2.992
7    2.414
8    2.267
9    2.611
Name: Target, dtype: float64

In [5]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
reg = RandomForestRegressor(n_estimators=100, random_state=42)

reg.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [6]:
reg.score(X_test, y_test)

0.8185203119376891

# Coefficient of determination

### R^2 = 1 - (sum(sqrt(yi) - sqrt(x1))) / (sum(sqrt(yi) - sqrt(yo)))
* `yi ---- həqiqi dəyərlər`
* `xi ---- praqnozlaşdırılmış dəyərlər`
* `yo ---- həqiqi dəyərlərin ortalaması`

In [7]:
from sklearn.metrics import r2_score
np.mean(y_test)

np.float64(2.086455184108527)

In [8]:
y_test_mean = np.full(len(y_test), np.mean(y_test))
np.shape(y_test), np.shape(y_test_mean), y_test_mean

((4128,),
 (4128,),
 array([2.08645518, 2.08645518, 2.08645518, ..., 2.08645518, 2.08645518,
        2.08645518]))

In [9]:
reg.score(X_test, y_test_mean)

0.0

In [10]:
r2_score(y_test, y_test_mean)

0.0

# r2-score ---- 1

In [11]:
r2_score(y_test, y_test)

1.0

# Mean absolute error (MAE)

In [12]:
from sklearn.metrics import mean_absolute_error
y_preds = reg.predict(X_test)
mean_absolute_error(y_test, y_preds)

0.3234577183624033

In [13]:
mae = pd.DataFrame(data = {
    "actual data" : y_test,
    "predicted data" : y_preds
})

mae["difference"] = y_test - y_preds
mae

       actual data  predicted data  difference
10771      2.45500        3.301341   -0.846341
230        1.69600        2.104960   -0.408960
17169      5.00001        4.617634    0.382376
8121       1.42600        1.335330    0.090670
15833      3.75000        3.800601   -0.050601
...            ...             ...         ...
17418      1.20400        1.667440   -0.463440
1407       1.79300        1.753220    0.039780
20201      2.34100        2.155870    0.185130
10286      2.45700        2.379610    0.077390
5524       3.31800        3.963343   -0.645343

[4128 rows x 3 columns]

In [14]:
mae["difference"].mean()

np.float64(-0.00998127955426315)

In [15]:
np.abs(mae['difference']).mean()

np.float64(0.3234577183624033)

# Mean squared error

In [16]:
mse = mae.copy()
mse["squared_difference"] = np.square(mse["difference"])
mse

       actual data  predicted data  difference  squared_difference
10771      2.45500        3.301341   -0.846341            0.716293
230        1.69600        2.104960   -0.408960            0.167248
17169      5.00001        4.617634    0.382376            0.146211
8121       1.42600        1.335330    0.090670            0.008221
15833      3.75000        3.800601   -0.050601            0.002560
...            ...             ...         ...                 ...
17418      1.20400        1.667440   -0.463440            0.214777
1407       1.79300        1.753220    0.039780            0.001582
20201      2.34100        2.155870    0.185130            0.034273
10286      2.45700        2.379610    0.077390            0.005989
5524       3.31800        3.963343   -0.645343            0.416468

[4128 rows x 4 columns]

In [17]:
mse['squared_difference'].mean()

np.float64(0.24380363059892937)

In [18]:
mse.iloc[:100, mse.columns.get_loc("squared_difference")] = 20
# mse.iloc[row, column]
# mse.loc[mse.index[:100], "squared_difference"] = 10
mse.head()

       actual data  predicted data  difference  squared_difference
10771      2.45500        3.301341   -0.846341                20.0
230        1.69600        2.104960   -0.408960                20.0
17169      5.00001        4.617634    0.382376                20.0
8121       1.42600        1.335330    0.090670                20.0
15833      3.75000        3.800601   -0.050601                20.0

In [19]:
mse['squared_difference']

10771    20.000000
230      20.000000
17169    20.000000
8121     20.000000
15833    20.000000
           ...
17418     0.214777
1407      0.001582
20201     0.034273
10286     0.005989
5524      0.416468
Name: squared_difference, Length: 4128, dtype: float64

# Cross validation score and scoring parameter

In [20]:
from sklearn.model_selection import cross_val_score
cv_r2 = cross_val_score(reg, X, y, cv=5, scoring=None)

In [21]:
cv_r2

array([0.51688816, 0.70429935, 0.74214734, 0.63501894, 0.68223973])

In [24]:
print(f"The cross validated coefficient of determination is : {np.mean(cv_r2)}")

The cross validated coefficient of determination is : 0.6561187027256853