# Describing Data with Pandas

In [1]:
import pandas as pd

![](pandas-anatomy-of-a-dataframe.png)

## Describing Data with Pandas

In [2]:
car_datas = pd.read_csv("car-sales.csv")

In [3]:
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [4]:
car_datas.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [11]:
## Attributes
car_datas.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [12]:
type(car_datas.columns)

pandas.core.indexes.base.Index

In [13]:
car_datas.columns[2]

'Odometer (KM)'

In [17]:
for item in car_datas.columns:
    print(item)

Make
Colour
Odometer (KM)
Doors
Price

In [20]:
## Index attribute
car_datas.index

RangeIndex(start=0, stop=10, step=1)

In [22]:
## Len built in fucntion
len(car_datas)

10

In [26]:
## Info method
car_datas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 528.0+ bytes

In [28]:
## Mean method
car_datas.mean(numeric_only = True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [29]:
car_datas["Doors"].mean()

np.float64(4.0)

In [33]:
## Sum method
result = car_datas["Odometer (KM)"].sum()
result

np.int64(786014)

In [35]:
## dtypes attribute
car_datas.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [37]:
car_datas.dtypes["Colour"]

dtype('O')

In [43]:
# Describe function
car_datas.describe()["Doors"]

count    10.000000
mean      4.000000
std       0.471405
min       3.000000
25%       4.000000
50%       4.000000
75%       4.000000
max       5.000000
Name: Doors, dtype: float64