# Manipulating data with pandas

In [ ]:
import pandas as pd

In [4]:
%matplotlib inline
import matplotlib.pyplot as plt

In [5]:
car_sales_missing_data = pd.read_csv("car-sales-missing-data.csv")

In [6]:
car_sales_missing_data

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [8]:
car_sales_missing_data.mean(numeric_only=True)

Odometer    92302.666667
Doors           4.000000
dtype: float64

In [9]:
car_sales_missing_data[car_sales_missing_data['Odometer'] > 50000]

     Make Colour  Odometer  Doors   Price
0  Toyota  White  150043.0    4.0  $4,000
1   Honda    Red   87899.0    4.0  $5,000
4  Nissan  White  213095.0    4.0  $3,500
8  Toyota  White   60000.0    NaN     NaN

In [12]:
car_sales_missing_data['Colour'].str.lower()

0    white
1      red
2     blue
3    black
4    white
5    green
6      NaN
7     blue
8    white
9    white
Name: Colour, dtype: object

In [13]:
car_sales_missing_data

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [14]:
car_sales_missing_data['Colour'] = car_sales_missing_data['Colour'].str.lower()

In [15]:
car_sales_missing_data

     Make Colour  Odometer  Doors    Price
0  Toyota  white  150043.0    4.0   $4,000
1   Honda    red   87899.0    4.0   $5,000
2  Toyota   blue       NaN    3.0   $7,000
3     BMW  black   11179.0    5.0  $22,000
4  Nissan  white  213095.0    4.0   $3,500
5  Toyota  green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   blue       NaN    4.0      NaN
8  Toyota  white   60000.0    NaN      NaN
9     NaN  white   31600.0    4.0   $9,700

In [16]:
pd.crosstab(car_sales_missing_data["Make"], car_sales_missing_data["Price"])

Price   $22,000  $3,500  $4,000  $4,500  $5,000  $7,000  $7,500
Make
BMW           1       0       0       0       0       0       0
Honda         0       0       0       0       1       0       1
Nissan        0       1       0       0       0       0       0
Toyota        0       0       1       1       0       1       0

In [18]:
car_sales_missing_data['Odometer'].fillna(car_sales_missing_data['Odometer'].mean(), inplace=True)

In [19]:
car_sales_missing_data

     Make Colour       Odometer  Doors    Price
0  Toyota  white  150043.000000    4.0   $4,000
1   Honda    red   87899.000000    4.0   $5,000
2  Toyota   blue   92302.666667    3.0   $7,000
3     BMW  black   11179.000000    5.0  $22,000
4  Nissan  white  213095.000000    4.0   $3,500
5  Toyota  green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   blue   92302.666667    4.0      NaN
8  Toyota  white   60000.000000    NaN      NaN
9     NaN  white   31600.000000    4.0   $9,700

# Manipulating data with pandas 2

In [47]:
car_datas = pd.read_csv("car-sales.csv")
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [53]:
car_datas["Price"] = car_datas['Price'].astype(str).str.replace(r"[^\d.]", "", regex = True).astype(float).round().astype(int)

In [54]:
car_datas

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [55]:
car_sales_missing_data

     Make Colour       Odometer  Doors    Price
0  Toyota  white  150043.000000    4.0   $4,000
1   Honda    red   87899.000000    4.0   $5,000
2  Toyota   blue   92302.666667    3.0   $7,000
3     BMW  black   11179.000000    5.0  $22,000
4  Nissan  white  213095.000000    4.0   $3,500
5  Toyota  green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   blue   92302.666667    4.0      NaN
8  Toyota  white   60000.000000    NaN      NaN
9     NaN  white   31600.000000    4.0   $9,700

In [56]:
car_sales_missing_data.dropna()

     Make Colour       Odometer  Doors    Price
0  Toyota  white  150043.000000    4.0   $4,000
1   Honda    red   87899.000000    4.0   $5,000
2  Toyota   blue   92302.666667    3.0   $7,000
3     BMW  black   11179.000000    5.0  $22,000
4  Nissan  white  213095.000000    4.0   $3,500
5  Toyota  green   92302.666667    4.0   $4,500

In [82]:
# Column from Series
gasoline_consumption_per_km = pd.Series([10, 9, 5, 30, 1])
car_datas["Gasoline_consumption_per_km"] = gasoline_consumption_per_km

In [83]:
car_datas

,Make,Colour,Odometer (KM),Doors,Price,gasoline_consumption_per_km,Gasoline_consumption_per_km
0,Toyota,White,150043,4,4000,10.0,10.0
1,Honda,Red,87899,4,5000,9.0,9.0
2,Toyota,Blue,32549,3,7000,5.0,5.0
3,BMW,Black,11179,5,22000,30.0,30.0
4,Nissan,White,213095,4,3500,1.0,1.0
5,Toyota,Green,99213,4,4500,5.0,NaN
6,Honda,Blue,45698,4,7500,5.0,NaN
7,Honda,Blue,54738,4,7000,5.0,NaN
8,Toyota,White,60000,4,6250,5.0,NaN
9,Nissan,White,31600,4,9700,5.0,NaN

In [86]:
car_datas['Gasoline_consumption_per_km'] = car_datas["Gasoline_consumption_per_km"].fillna(5)

In [87]:
car_datas

,Make,Colour,Odometer (KM),Doors,Price,gasoline_consumption_per_km,Gasoline_consumption_per_km
0,Toyota,White,150043,4,4000,10.0,10.0
1,Honda,Red,87899,4,5000,9.0,9.0
2,Toyota,Blue,32549,3,7000,5.0,5.0
3,BMW,Black,11179,5,22000,30.0,30.0
4,Nissan,White,213095,4,3500,1.0,1.0
5,Toyota,Green,99213,4,4500,5.0,5.0
6,Honda,Blue,45698,4,7500,5.0,5.0
7,Honda,Blue,54738,4,7000,5.0,5.0
8,Toyota,White,60000,4,6250,5.0,5.0
9,Nissan,White,31600,4,9700,5.0,5.0

In [89]:
# Column from Python List
car_seats = []
for i in range(len(car_datas)):
    car_seats.append(5)
car_datas['Seats'] = car_seats

In [90]:
car_datas

,Make,Colour,Odometer (KM),Doors,Price,gasoline_consumption_per_km,Gasoline_consumption_per_km,Seats
0,Toyota,White,150043,4,4000,10.0,10.0,5
1,Honda,Red,87899,4,5000,9.0,9.0,5
2,Toyota,Blue,32549,3,7000,5.0,5.0,5
3,BMW,Black,11179,5,22000,30.0,30.0,5
4,Nissan,White,213095,4,3500,1.0,1.0,5
5,Toyota,Green,99213,4,4500,5.0,5.0,5
6,Honda,Blue,45698,4,7500,5.0,5.0,5
7,Honda,Blue,54738,4,7000,5.0,5.0,5
8,Toyota,White,60000,4,6250,5.0,5.0,5
9,Nissan,White,31600,4,9700,5.0,5.0,5

In [93]:
# 
car_datas["Gasoline consumption so far (L)"] = car_datas['Odometer (KM)'] * car_datas['Gasoline_consumption_per_km'] / 100

In [94]:
car_datas

,Make,Colour,Odometer (KM),Doors,Price,gasoline_consumption_per_km,Gasoline_consumption_per_km,Seats,Gasoline consumption so far,Gasoline consumption so far (L)
0,Toyota,White,150043,4,4000,10.0,10.0,5,15004.30,15004.30
1,Honda,Red,87899,4,5000,9.0,9.0,5,7910.91,7910.91
2,Toyota,Blue,32549,3,7000,5.0,5.0,5,1627.45,1627.45
3,BMW,Black,11179,5,22000,30.0,30.0,5,3353.70,3353.70
4,Nissan,White,213095,4,3500,1.0,1.0,5,2130.95,2130.95
5,Toyota,Green,99213,4,4500,5.0,5.0,5,4960.65,4960.65
6,Honda,Blue,45698,4,7500,5.0,5.0,5,2284.90,2284.90
7,Honda,Blue,54738,4,7000,5.0,5.0,5,2736.90,2736.90
8,Toyota,White,60000,4,6250,5.0,5.0,5,3000.00,3000.00
9,Nissan,White,31600,4,9700,5.0,5.0,5,1580.00,1580.00

In [106]:
car_datas  = car_datas.drop("gasoline_consumption_per_km", axis=1)

In [107]:
car_datas

,Make,Colour,Odometer (KM),Doors,Price,Gasoline_consumption_per_km,Seats,Gasoline consumption so far (L)
0,Toyota,White,150043,4,4000,10.0,5,15004.30
1,Honda,Red,87899,4,5000,9.0,5,7910.91
2,Toyota,Blue,32549,3,7000,5.0,5,1627.45
3,BMW,Black,11179,5,22000,30.0,5,3353.70
4,Nissan,White,213095,4,3500,1.0,5,2130.95
5,Toyota,Green,99213,4,4500,5.0,5,4960.65
6,Honda,Blue,45698,4,7500,5.0,5,2284.90
7,Honda,Blue,54738,4,7000,5.0,5,2736.90
8,Toyota,White,60000,4,6250,5.0,5,3000.00
9,Nissan,White,31600,4,9700,5.0,5,1580.00

In [108]:
# Create column from a single value
car_datas["Wheels"] = 4

In [109]:
car_datas

,Make,Colour,Odometer (KM),Doors,Price,Gasoline_consumption_per_km,Seats,Gasoline consumption so far (L),Wheels
0,Toyota,White,150043,4,4000,10.0,5,15004.30,4
1,Honda,Red,87899,4,5000,9.0,5,7910.91,4
2,Toyota,Blue,32549,3,7000,5.0,5,1627.45,4
3,BMW,Black,11179,5,22000,30.0,5,3353.70,4
4,Nissan,White,213095,4,3500,1.0,5,2130.95,4
5,Toyota,Green,99213,4,4500,5.0,5,4960.65,4
6,Honda,Blue,45698,4,7500,5.0,5,2284.90,4
7,Honda,Blue,54738,4,7000,5.0,5,2736.90,4
8,Toyota,White,60000,4,6250,5.0,5,3000.00,4
9,Nissan,White,31600,4,9700,5.0,5,1580.00,4