In [1]:
import pandas as pd

In [2]:
car_datas = pd.read_csv("car-sales.csv")

In [3]:
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [11]:
# Shuffling data 
shuffled_data = car_datas.sample(frac=1)

In [12]:
shuffled_data

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
2  Toyota   Blue          32549      3   $7,000.00
4  Nissan  White         213095      4   $3,500.00
7   Honda   Blue          54738      4   $7,000.00
3     BMW  Black          11179      5  $22,000.00
8  Toyota  White          60000      4   $6,250.00
1   Honda    Red          87899      4   $5,000.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
9  Nissan  White          31600      4   $9,700.00

In [15]:
# Does not show indexes created when there is a shuffle
shuffled_data.reset_index(drop=True)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1  Toyota   Blue          32549      3   $7,000.00
2  Nissan  White         213095      4   $3,500.00
3   Honda   Blue          54738      4   $7,000.00
4     BMW  Black          11179      5  $22,000.00
5  Toyota  White          60000      4   $6,250.00
6   Honda    Red          87899      4   $5,000.00
7  Toyota  Green          99213      4   $4,500.00
8   Honda   Blue          45698      4   $7,500.00
9  Nissan  White          31600      4   $9,700.00

In [19]:
shuffled_data['Odometer (KM)'] = shuffled_data['Odometer (KM)'].apply(lambda x:x / 1.6).round()

In [20]:
shuffled_data

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White        36632.0      4   $4,000.00
2  Toyota   Blue         7947.0      3   $7,000.00
4  Nissan  White        52025.0      4   $3,500.00
7   Honda   Blue        13364.0      4   $7,000.00
3     BMW  Black         2729.0      5  $22,000.00
8  Toyota  White        14648.0      4   $6,250.00
1   Honda    Red        21460.0      4   $5,000.00
5  Toyota  Green        24222.0      4   $4,500.00
6   Honda   Blue        11157.0      4   $7,500.00
9  Nissan  White         7715.0      4   $9,700.00