# NumPy sort arrays

In [2]:
import numpy as np
import pandas as pd

In [66]:
a1 = np.array([10, 55, 3, 100])
a1

array([ 10,  55,   3, 100])

In [34]:
rng = np.random.default_rng(100)
a2 = rng.integers(0, 10, (2, 3))
a2

array([[7, 8, 1],
       [5, 0, 2]])

In [35]:
sorted_a1 = np.sort(a1)
sorted_a1

array([  3,  10,  55, 100])

In [36]:
np.sort(a2, axis = 0)

array([[5, 0, 1],
       [7, 8, 2]])

In [37]:
np.sort(a2)

array([[1, 7, 8],
       [0, 2, 5]])

In [38]:
np.argmax(a1)

np.int64(3)

In [39]:
np.argmin(a1)

np.int64(2)

In [40]:
a2

array([[7, 8, 1],
       [5, 0, 2]])

In [41]:
np.argmax(a2, axis = 0)

array([0, 0, 1])

# NumPy sort array descending

In [67]:
a2_dataframe = pd.DataFrame(a2, index = ["Math", "English"], columns = ["1", "3", "5"])
a2_dataframe

         1  3  5
Math     7  8  1
English  5  0  2

In [68]:
a1, a1.shape

(array([ 10,  55,   3, 100]), (4,))

In [69]:
columns = np.array([1, 3, 5, 7])

In [70]:
a1_dataframe = pd.DataFrame(a1.reshape(1, 4), index = ["Student"], columns = columns)
a1_dataframe

          1   3  5    7
Student  10  55  3  100

In [76]:
indexes = np.argsort(a1)[::-1]
indexes

array([3, 2, 1, 0])

In [77]:
a1 = a1[indexes]
a1

array([100,  55,  10,   3])

In [78]:
columns = columns[indexes]
columns

array([7, 3, 1, 5])

In [79]:
a1_dataframe

         5   1   3    7
Student  3  10  55  100

In [80]:
a1_dataframe =  pd.DataFrame(a1.reshape(1, 4), index = ["Student"], columns = columns)
a1_dataframe

           7   3   1  5
Student  100  55  10  3

In [84]:
a1_than_20 = a1_dataframe[a1_dataframe[7] > 20]
a1_than_20

           7   3   1  5
Student  100  55  10  3

In [94]:
a1_than_20[5]

Student    3
Name: 5, dtype: int64

In [96]:
a2_dataframe

         1  3  5
Math     7  8  1
English  5  0  2

In [123]:
cols = a2_dataframe.loc["Math"] > 5
a2_dataframe.loc[["Math", "English"], result]

         1  3
Math     7  8
English  5  0