In [2]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [26]:
car_datas = pd.read_csv("car-sales.csv")
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [5]:
car_datas["Price"] = car_datas["Price"].astype(str).str.replace(r"[^\d.]", "", regex = True).astype(float).astype(int)

In [6]:
car_datas

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [8]:
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [27]:
car_datas["Price"] = car_datas["Price"].astype(str).str.replace(r"[^\d]", "", regex=True).astype(int)
car_datas

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White         150043      4   400000
1   Honda    Red          87899      4   500000
2  Toyota   Blue          32549      3   700000
3     BMW  Black          11179      5  2200000
4  Nissan  White         213095      4   350000
5  Toyota  Green          99213      4   450000
6   Honda   Blue          45698      4   750000
7   Honda   Blue          54738      4   700000
8  Toyota  White          60000      4   625000
9  Nissan  White          31600      4   970000

In [28]:
car_datas["Price"] = car_datas['Price'].astype(str).str[:-2].astype(int)

In [29]:
car_datas

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [21]:
car_datas = car_datas.drop("Doors", axis = 1)

In [22]:
car_datas

     Make Colour  Odometer (KM)  Price
0  Toyota  White         150043     40
1   Honda    Red          87899     50
2  Toyota   Blue          32549     70
3     BMW  Black          11179    220
4  Nissan  White         213095     35
5  Toyota  Green          99213     45
6   Honda   Blue          45698     75
7   Honda   Blue          54738     70
8  Toyota  White          60000     62
9  Nissan  White          31600     97

In [30]:
car_datas

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [32]:
car_datas[car_datas["Odometer (KM)"] > 30000]

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White      93776.875      4   4000
1   Honda    Red      54936.875      4   5000
4  Nissan  White     133184.375      4   3500
5  Toyota  Green      62008.125      4   4500
7   Honda   Blue      34211.250      4   7000
8  Toyota  White      37500.000      4   6250

In [33]:
car_datas["Price per (KM)"] = car_datas['Price'] / car_datas['Odometer (KM)']

In [34]:
car_datas

     Make Colour  Odometer (KM)  Doors  Price  Price per (KM)
0  Toyota  White      93776.875      4   4000        0.042654
1   Honda    Red      54936.875      4   5000        0.091014
2  Toyota   Blue      20343.125      3   7000        0.344097
3     BMW  Black       6986.875      5  22000        3.148761
4  Nissan  White     133184.375      4   3500        0.026279
5  Toyota  Green      62008.125      4   4500        0.072571
6   Honda   Blue      28561.250      4   7500        0.262594
7   Honda   Blue      34211.250      4   7000        0.204611
8  Toyota  White      37500.000      4   6250        0.166667
9  Nissan  White      19750.000      4   9700        0.491139

In [31]:
car_datas['Odometer (KM)'] = car_datas['Odometer (KM)'].apply(lambda x: x / 1.6)
car_datas

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White      93776.875      4   4000
1   Honda    Red      54936.875      4   5000
2  Toyota   Blue      20343.125      3   7000
3     BMW  Black       6986.875      5  22000
4  Nissan  White     133184.375      4   3500
5  Toyota  Green      62008.125      4   4500
6   Honda   Blue      28561.250      4   7500
7   Honda   Blue      34211.250      4   7000
8  Toyota  White      37500.000      4   6250
9  Nissan  White      19750.000      4   9700

In [35]:
car_datas.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price', 'Price per (KM)'], dtype='object')

In [38]:
car_datas

     Make Colour  Odometer (KM)  Doors  Price  Price per (KM)
0  Toyota  White      93776.875      4   4000        0.042654
1   Honda    Red      54936.875      4   5000        0.091014
2  Toyota   Blue      20343.125      3   7000        0.344097
3     BMW  Black       6986.875      5  22000        3.148761
4  Nissan  White     133184.375      4   3500        0.026279
5  Toyota  Green      62008.125      4   4500        0.072571
6   Honda   Blue      28561.250      4   7500        0.262594
7   Honda   Blue      34211.250      4   7000        0.204611
8  Toyota  White      37500.000      4   6250        0.166667
9  Nissan  White      19750.000      4   9700        0.491139

In [42]:
car_datas.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price', 'Price per (KM)'], dtype='object')

In [46]:
car_datas = car_datas.rename(columns={"Odometer (KM)": "Odometer (MI)", "Price per (KM)" : "Price per (MI)"})
car_datas

     Make Colour  Odometer (MI)  Doors  Price  Price per (MI)
0  Toyota  White      93776.875      4   4000        0.042654
1   Honda    Red      54936.875      4   5000        0.091014
2  Toyota   Blue      20343.125      3   7000        0.344097
3     BMW  Black       6986.875      5  22000        3.148761
4  Nissan  White     133184.375      4   3500        0.026279
5  Toyota  Green      62008.125      4   4500        0.072571
6   Honda   Blue      28561.250      4   7500        0.262594
7   Honda   Blue      34211.250      4   7000        0.204611
8  Toyota  White      37500.000      4   6250        0.166667
9  Nissan  White      19750.000      4   9700        0.491139

In [49]:
a1 = np.array([1, 2, 4])
a1.dtype

dtype('int64')

# Linear space

In [57]:
a2 = np.linspace(0, 100, num = 16)
a2

array([  0.        ,   6.66666667,  13.33333333,  20.        ,
        26.66666667,  33.33333333,  40.        ,  46.66666667,
        53.33333333,  60.        ,  66.66666667,  73.33333333,
        80.        ,  86.66666667,  93.33333333, 100.        ])