# Pandas exercise 1

## Pandas anatomy of a dataframes

![](pandas-anatomy-of-a-dataframe.png)

## 2 main data types

### Series and dataframes

In [3]:
import pandas as pd

In [4]:
car_brands = pd.Series(["BMW", "Mercedes", "Opel", "Audi"])

In [5]:
car_brands

0         BMW
1    Mercedes
2        Opel
3        Audi
dtype: object

#### Series ----- 1 dimensional

In [6]:
car_colours = pd.Series(["Red", "Black", "Gray"])

#### DataFrames ----- 2 dimensional

In [10]:
car_datas = pd.DataFrame({"car_brands": car_brands, "car_colours": car_colours})

In [11]:
car_datas

  car_brands car_colours
0        BMW         Red
1   Mercedes       Black
2       Opel        Gray
3       Audi         NaN

In [15]:
car_datas = pd.read_csv("car-sales.csv")
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [25]:
car_datas.to_csv("exported_car_datas", index = False)

In [26]:
exported_car_datas = pd.read_csv("exported_car_datas")

In [27]:
exported_car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## Data from URLs

In [28]:
heart_disease = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/heart-disease.csv")

In [29]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [31]:
car_datas.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [35]:
car_datas.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64