# Viewing and selecting data with pandas

![](pandas-anatomy-of-a-dataframe.png)

In [1]:
import pandas as pd

In [4]:
car_datas = pd.read_csv("car-sales.csv")
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [6]:
car_datas.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [7]:
car_datas.head(8)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00

In [8]:
car_datas.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [9]:
car_datas.tail(2)

     Make Colour  Odometer (KM)  Doors      Price
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [10]:
car_datas.tail(2)["Price"]

8    $6,250.00
9    $9,700.00
Name: Price, dtype: object

In [14]:
last_2_car = car_datas.tail(2)
last_2_car

     Make Colour  Odometer (KM)  Doors      Price
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [15]:
last_2_car.Price

8    $6,250.00
9    $9,700.00
Name: Price, dtype: object

In [20]:
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [21]:
animals = pd.Series(["cat", "panda", "cow", "dog"], index = [3, 4, 9, 100])

In [35]:
animals

3        cat
4      panda
9        cow
100      dog
dtype: object

In [49]:
# loc refers to index
animals.loc[3]

'cat'

In [48]:
# CTRL + SHIFT + -

In [50]:
# iloc refers to position
animals.iloc[2]

'cow'

In [51]:
animals.loc[:9]

3      cat
4    panda
9      cow
dtype: object

In [44]:
animals.iloc[:2:-1]

100    dog
dtype: object

In [45]:
animals.iloc[::-1]

100      dog
9        cow
4      panda
3        cat
dtype: object

In [52]:
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [53]:
car_datas.loc[4]

Make                Nissan
Colour               White
Odometer (KM)       213095
Doors                    4
Price            $3,500.00
Name: 4, dtype: object

In [54]:
car_datas.iloc[4]

Make                Nissan
Colour               White
Odometer (KM)       213095
Doors                    4
Price            $3,500.00
Name: 4, dtype: object

In [55]:
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [58]:
for key, value in car_datas.items():
    print(key, value)

Make 0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object
Colour 0    White
1      Red
2     Blue
3    Black
4    White
5    Green
6     Blue
7     Blue
8    White
9    White
Name: Colour, dtype: object
Odometer (KM) 0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64
Doors 0    4
1    4
2    3
3    5
4    4
5    4
6    4
7    4
8    4
9    4
Name: Doors, dtype: int64
Price 0     $4,000.00
1     $5,000.00
2     $7,000.00
3    $22,000.00
4     $3,500.00
5     $4,500.00
6     $7,500.00
7     $7,000.00
8     $6,250.00
9     $9,700.00
Name: Price, dtype: object

In [59]:
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [62]:
car_datas[car_datas["Make"] == "Toyota"]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
2  Toyota   Blue          32549      3  $7,000.00
5  Toyota  Green          99213      4  $4,500.00
8  Toyota  White          60000      4  $6,250.00

In [63]:
car_datas[car_datas["Odometer (KM)"] > 65000 ]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
4  Nissan  White         213095      4  $3,500.00
5  Toyota  Green          99213      4  $4,500.00

In [64]:
car_datas

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [80]:
result2 = car_datas[(car_datas["Make"] == "Honda") | (car_datas['Odometer (KM)'] > 50000)]
result2

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
4  Nissan  White         213095      4  $3,500.00
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00

In [76]:
result2.loc[7]

Make                 Honda
Colour                Blue
Odometer (KM)        54738
Doors                    4
Price            $7,000.00
Name: 7, dtype: object

In [81]:
car_datas.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object